<a href="https://colab.research.google.com/github/chrismoroney/TensorFlow-practice/blob/main/sequences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [2]:
tokenizer = Tokenizer()

In [5]:
data = "Once upon a time there was a prince and princess."
corpus = data.lower().split("\n")

In [7]:
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index)+1

In [8]:
print(tokenizer.word_index)

{'a': 1, 'once': 2, 'upon': 3, 'time': 4, 'there': 5, 'was': 6, 'prince': 7, 'and': 8, 'princess': 9}


In [9]:
input_sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
      n_gram_sequence = token_list[:i+1]
      input_sequences.append(n_gram_sequence)
print(input_sequences[:5])

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [2, 3, 1, 4, 5, 6]]


In [11]:
#padded sequences
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

In [12]:
print(input_sequences)

[[0 0 0 0 0 0 0 0 2 3]
 [0 0 0 0 0 0 0 2 3 1]
 [0 0 0 0 0 0 2 3 1 4]
 [0 0 0 0 0 2 3 1 4 5]
 [0 0 0 0 2 3 1 4 5 6]
 [0 0 0 2 3 1 4 5 6 1]
 [0 0 2 3 1 4 5 6 1 7]
 [0 2 3 1 4 5 6 1 7 8]
 [2 3 1 4 5 6 1 7 8 9]]
